### ISSUE TITLE
typo: Doc typo in compose-en.md and compose-zh-cn.md

### ISSUE THREAD

**Issue by KSARK** [viosey/material-theme-docs#4]
[这一行](https://github.com/viosey/material-theme-docs/blame/master/compose-zh-cn.md#L160)应写做`「标签云」页面`而非`「图库」页面`  
[这一行](https://github.com/viosey/material-theme-docs/blame/master/compose-en.md#L173)应写做`the Tag Cloud page`而非`the Gallery page`  
不知道是不是故意的_(:з)∠)_

**Comment by iblh** [comment]
因为复制到时候没有注意到…
你可以帮忙提交 PR，或者我之后修复

**Comment by KSARK** [comment]
PR已提交~

**Comment by iblh** [comment]
#5
